#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# datetime:2019/8/1 14:47
import subprocess as sp

tables_v430=["COORDINATE","DIANPING_INFO","FORECAST_WEEK","PEOPLE_STREAM","RENT_INFO","STATISTICS_DATA","TOBACCO.AREA","TOBACCO.BLOCK_DATA","TOBACCO.CODE",
 "TOBACCO.DATA_INDEX","TOBACCO.RETAIL","TOBACCO.RETAIL_ANALYSIS","TOBACCO.RETAIL_WARNING","TOBACCO.WARNING_CODE","TOBACCO.WARNING_TYPE"]

tables_v530=["V530_.COORDINATE","V530_.DIANPING_INFO","V530_.FORECAST_WEEK","V530_.PEOPLE_STREAM","V530_.RENT_INFO","V530_.STATISTICS_DATA",
             "V530_TOBACCO.AREA","V530_TOBACCO.BLOCK_DATA","V530_TOBACCO.CODE","V530_TOBACCO.DATA_INDEX","V530_TOBACCO.RETAIL","V530_TOBACCO.WARNING_CODE",
             "V530_TOBACCO.WARNING_TYPE"]

tables_v630=["V630_.COORDINATE","V630_.DIANPING_INFO","V630_.FORECAST_WEEK","V630_.PEOPLE_STREAM","V630_.RENT_INFO","V630_.STATISTICS_DATA",
              "V630_TOBACCO.AREA","V630_TOBACCO.BLOCK_DATA","V630_TOBACCO.BRAND_DATA","V630_TOBACCO.CIGA_GRADE","V630_TOBACCO.CIGA_PICTURE",
              "V630_TOBACCO.CIGA_STATIC","V630_TOBACCO.CODE","V630_TOBACCO.DATA_INDEX","V630_TOBACCO.GEARS_TOSS","V630_TOBACCO.RETAIL",
              "V630_TOBACCO.RETAIL_WARNING","V630_TOBACCO.WARNING_CODE","V630_TOBACCO.WARNING_TYPE"]


tables=[tables_v430,tables_v530,tables_v630]
for i in tables:
    for table in i:
       command=f"hbase org.apache.hadoop.hbase.mapreduce.Export -Dmapred.output.compress=true {table}  ./hbase_bak/{table}"
       sp.check_output(command,shell=True)
